### PR TITLE
Add Accounting section.

### PR DESCRIPTION
**Pull request by wdaher**
A section for deals for startups related to accounting/finance/bookkeeping/etc.

### CODE REVIEW

**Comment by wdaher** [comment]
Rationale on Pilot, specifically: specializes exclusively in startup bookkeeping (particularly early-stage startups).

Plan for early-stage startups (technically, for HN readers) is here: https://pilot.com/partner/hn/

**Comment by dakshshah96** [comment]
Hey 👋 	

Thanks for the suggestion!

I'm not so sure if this should be included in a list where we're promising free/discounted plans specifically for startups. Even after their HN discount, their pricing is significantly higher than other services listed here.

Let me know what you think!

**Comment by wdaher** [comment]
Hi! Totally up to you—I think the biggest difference here is that Pilot is an actual _bookkeeping service_ (i.e. a human who does your bookkeeping, with software assistance) as opposed to a software tool, which is why it seems more expensive.

Having said that, if you're trying to focus exclusively on free tools, I agree, it shouldn't be included.

**Comment by dakshshah96** [comment]
I think we should keep the focus exclusively on free/discounted services offered to startups in specific for now.

Thank you for your time! 🙏

**Pull request closed without merging**
